[package]
name = "rust-excercices"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.14"
solana-client = "1.14"
base58 = "0.2.0"
dotenv = "0.15"
ed25519-dalek = "1.0.1"
tokio = { version = "1", features = ["full"] }